version: '3.8'

services:
  leaderboard-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: leaderboard-api:latest
    container_name: leaderboard-api
    environment:
      CLICKHOUSE_ADDR: "clickhouse:9000"
      CLICKHOUSE_DB: "default"
      CLICKHOUSE_USER: "default"
      CLICKHOUSE_PASSWORD: "clickhouse_password"
      REFRESH: "true"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      REDIS_PASSWORD: "8fh21f289j2ıfhjıvs844"
    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on:
      redis:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
    restart: on-failure

  redis:
    image: redis:7.0-alpine
    container_name: redis
    command: [ "redis-server", "--requirepass", "8fh21f289j2ıfhjıvs844" ]
    ports:
      - "6379:6379"
    networks:
      - backend
    volumes:
      - redis-data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "8fh21f289j2ıfhjıvs844", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    environment:
      CLICKHOUSE_DB: "default"
      CLICKHOUSE_USER: "default"
      CLICKHOUSE_PASSWORD: "clickhouse_password"
    ports:
      - "9000:9000"
      - "8123:8123"
    networks:
      - backend
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    healthcheck:
      test: [ "CMD", "clickhouse-client", "--password", "clickhouse_password", "--query", "SELECT 1" ]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  backend:
    driver: bridge

volumes:
  redis-data:
    driver: local
  clickhouse-data:
    driver: local
